version: '3'

services:
  postgres:
    container_name: pg-docker
    image: postgres
    volumes:
    - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
      - POSTGRES_PASSWORD=docker
    networks:
      - db

  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management
    ports:
    - 15672:15672
    networks:
      - query

  publisher:
    build:
      dockerfile: ./Dockerfile.publisher
    container_name: event-publisher
    depends_on:
      - rabbit
    networks:
      - query

networks:
  db:
    driver: bridge
  query:
    driver: bridge