version: '3'

services:
  postgres:
    container_name: pg-docker
    image: postgres
    volumes:
    - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
      - POSTGRES_PASSWORD=docker

  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management
    ports:
    - 5672:5672
    - 15672:15672