version: '3'

services:
  postgres:
    container_name: pg-docker
    image: postgres
    volumes:
    - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
      - POSTGRES_PASSWORD=docker